# feedebasbaseer
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/smarthome/xsub/val_data_joint.npy
  label_path: ./data/smarthome/xsub/val_label.pkl
  debug: False 

# model
model: model.baseline_smarthome.Model  
model_args:
  num_class: 31
  num_point: 17
  num_person: 2
  in_channels: 2
  #num_heads: 3
  #tau: 1
  graph: graph.smarthome.Graph
# test
phase: test
device: [0,1]
test_batch_size: 32

weights: ./runs/smarthome/smarthome_cs_unik_joint-49-33350.pt
work_dir: ./eval/smarthome/xsub/joint/
save_score: True

