
work_dir: ./work_dir/smarthome/xsub/baseline_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/smarthome/xsub/train_data_joint.npy
  label_path: ./data/smarthome/xsub/train_label.pkl
  debug: False
  random_choose: True
  random_shift: False
  random_move: False
  window_size: 400
  normalization: False

test_feeder_args:
  data_path: ./data/smarthome/xsub/val_data_joint.npy
  label_path: ./data/smarthome/xsub/val_label.pkl
  debug: False
  random_choose: True
  window_size: 400

# model
model: model.baseline_smarthome.Model  
model_args:
  #weights: ./weights/weights-posetics.pt
  #weights: 'no'
  num_class: 31
  num_point: 17
  num_person: 2
  #backbone_fixed: False # True for linear classification
  in_channels: 2
  #num_heads: 3
  #tau: 1
  graph: graph.smarthome.Graph

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [35, 45]
warm_up_epoch: 5

# training
device: [0, 1,2,3]
batch_size:  48      #64
forward_batch_size: 24      #32
test_batch_size:  48      #64
num_epoch: 55
nesterov: True

