work_dir: ./work_dir/ntu60/xview/baseline_bone

# feeder
feeder: feeders.ctr_feeder.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: True

test_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.baseline.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.AdjMatrixGraph

#optim
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
num_epoch: 65
device: [0]
batch_size: 256
forward_batch_size: 256
test_batch_size: 256
nesterov: True