
# feeder
feeder: feeders.ctr_feeder.Feeder

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: True
  debug: False

# model
model: model.baseline.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# test
phase: test
device: [0]
test_batch_size: 256
weights: ./pretrained_models/ntu60_xsub_bone.pt

work_dir: ./eval/ntu/xsub/bone/
save_score: True